### ISSUE TITLE
Signed assembly in NuGet

### ISSUE THREAD

**Issue by Atrejoe** [hey-red/Markdown#71]
Would you mind signing the assembly on NuGet? I'm trying to create a Windows Preview Pane handler, which requires my assembly to be signed.

_If I get it up and running, I'll open-source it too of course._

**Comment by Kiri-rin** [comment]
I've updated package in Nuget. Let me know if the signature is incorrect.

**Comment by Atrejoe** [comment]
Wow that was a lightning response! Works like a charm, once I get a decent installer I'll publish the extension and thank you!

**Comment by Atrejoe** [comment]
@Kiri-rin : As promised: https://github.com/Atrejoe/MarkdownPreview (I still have a buig to squash and and installer to make)

**Comment by nul800sebastiaan** [comment]
In which version was this assembly signed? Just as an FYI, you should never do this in a patch version, as commented here: https://github.com/AutoMapper/AutoMapper/issues/373#issuecomment-127644405

Also note that your dll's File Version and your Product version don't match:
![image](https://cloud.githubusercontent.com/assets/304656/16945907/6345769a-4da7-11e6-84fb-8e7a3805dc21.png)

And last remark: we have a dependency on this dll in Umbraco and I was about to update it but couldn't find any release notes for the latest versions. It would be good if you could tag the appropriate commit that goes with the release so we can see if we can update to the latest. Currently, this fix is most likely blocking us from upgrading beyond 1.14.4, which we ship with currently.

**Comment by hey-red** [comment]
@nul800sebastiaan 
>In which version was this assembly signed? 
1.14.5 and never versions (if I not forgotten). i.e I need to use major version?

Fix and updated package will come later.

**Comment by TonnyMediamonks** [comment]
I also commented the following at the referenced AutoMapper issue: 

If you hook into the AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve event and remove the publickey from the ResolveEventArgs.Name and pass that again in Assembly.Load("string with publickey removed") and return that assembly. The appdomain will load the dll with or without a SN token / publickey token.

Currently doing it for this markdown sharp dll in umbraco 7.4.3

**Comment by hey-red** [comment]
Package updated.
